from pydantic import BaseModel
from datetime import datetime
from typing import Optional

# from enum import Enum
from models.tasks import TaskPriority, TaskStatus


class TaskBase(BaseModel):
    title: str
    description: str
    # created_at: datetime # autogenerated by db
    due_at: datetime | None
    completed: bool
    owner_id: int
    status: TaskStatus = TaskStatus.TODO
    priority: TaskPriority = TaskPriority.LOW


class TaskCreate(TaskBase):
    pass


class TaskUpdate(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    due_at: Optional[datetime] = None
    completed: Optional[bool] = None
    status: Optional[TaskStatus] = None
    priority: Optional[TaskPriority] = None


class Task(TaskBase):
    id: int
    created_at: datetime

    class config:
        model_config = {"from_attributes": True}
